### ISSUE TITLE
device not triggering mouse clicks

### ISSUE THREAD

**Issue by BoostedMoose** [pyinput/python-uinput#4]
Thank you for this brilliant little library.

Unfortunately, I don't get the mouse button clicks to work. Everything else works fine. Is there a specific syntax I need to consider when emitting mouse clicks?

I tried the following:
device.emit(uinput.BTN_LEFT, 1)
device.emit_click(uinput.BTN_LEFT)

Using a Raspberry Pi 5 with Bookworm and Wayland.

**Comment by gitanat** [comment]
Have you tried running the examples? Sometimes a `sleep` is needed before emitting events. It might also be a problem related to wayland, see #3 for debugging tips

**Comment by BoostedMoose** [comment]
Thanks for your answer. I could actually resolve it.

You need to use These commands to emit a click:

device.emit(uinput.BTN_LEFT, 1) #Mouse down
device.emit(uinput.BTN_LEFT, 0) #Mouse up

Would be great if you can include this in the documentation.
